<a href="https://colab.research.google.com/github/trunX04/Iris-Flower-Classification/blob/main/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/iris.csv',header=None)
df = df.drop(0)
df

0    1    2    3          4
1    5.1  3.5  1.4   .2     Setosa
2    4.9    3  1.4   .2     Setosa
3    4.7  3.2  1.3   .2     Setosa
4    4.6  3.1  1.5   .2     Setosa
5      5  3.6  1.4   .2     Setosa
..   ...  ...  ...  ...        ...
146  6.7    3  5.2  2.3  Virginica
147  6.3  2.5    5  1.9  Virginica
148  6.5    3  5.2    2  Virginica
149  6.2  3.4  5.4  2.3  Virginica
150  5.9    3  5.1  1.8  Virginica

[150 rows x 5 columns]

In [ ]:
df.columns=["Sepallengthincm","Sepalwidthincm","Petallengthincm","Petalwidthincm","Class"]
df

Sepallengthincm Sepalwidthincm Petallengthincm Petalwidthincm      Class
1               5.1            3.5             1.4             .2     Setosa
2               4.9              3             1.4             .2     Setosa
3               4.7            3.2             1.3             .2     Setosa
4               4.6            3.1             1.5             .2     Setosa
5                 5            3.6             1.4             .2     Setosa
..              ...            ...             ...            ...        ...
146             6.7              3             5.2            2.3  Virginica
147             6.3            2.5               5            1.9  Virginica
148             6.5              3             5.2              2  Virginica
149             6.2            3.4             5.4            2.3  Virginica
150             5.9              3             5.1            1.8  Virginica

[150 rows x 5 columns]

In [ ]:
X = df.drop(["Class"],axis=1)
y = df["Class"]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)


In [ ]:
y_pred

array(['Versicolor', 'Setosa', 'Virginica', 'Versicolor', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Versicolor',
       'Virginica', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Virginica', 'Virginica',
       'Virginica', 'Virginica', 'Setosa', 'Setosa'], dtype='<U10')

In [ ]:
y_test

74     Versicolor
19         Setosa
119     Virginica
79     Versicolor
77     Versicolor
32         Setosa
65     Versicolor
142     Virginica
69     Versicolor
83     Versicolor
111     Virginica
13         Setosa
37         Setosa
10         Setosa
20         Setosa
57     Versicolor
105     Virginica
70     Versicolor
56     Versicolor
133     Virginica
30         Setosa
128     Virginica
27         Setosa
129     Virginica
132     Virginica
146     Virginica
109     Virginica
144     Virginica
46         Setosa
31         Setosa
Name: Class, dtype: object

In [ ]:
import sklearn.metrics

labelsss = ['Versicolor', 'Setosa', 'Virginica']
print(sklearn.metrics.confusion_matrix(y_test, y_pred, labels=labelsss))

[[ 9  0  0]
 [ 0 10  0]
 [ 0  0 11]]
